name: Lint
on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-v16-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Install dependencies
        run: yarn
      - name: Fetch base branch
        run: git fetch --depth 1 origin ${GITHUB_BASE_REF}
      - name: Run lint
        run: |
          git diff origin/${GITHUB_BASE_REF} HEAD --name-only --diff-filter=AMR -- 'src/**/*.js' 'src/**/*.ts' 'src/**/*.tsx' \
          | xargs yarn lint:github-actions
