name: next-build
on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**
jobs:
  next-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: node-v16-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Install dependencies
        run: yarn
      - name: Run next build
        run: yarn run build
